// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: grpc/grpc.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetadataKey int32

const (
	MetadataKey_Exif_DateTime     MetadataKey = 0
	MetadataKey_Exif_Make         MetadataKey = 1
	MetadataKey_Exif_Model        MetadataKey = 2
	MetadataKey_Exif_Orientation  MetadataKey = 3
	MetadataKey_Exif_FocalLength  MetadataKey = 4
	MetadataKey_Exif_ExposureTime MetadataKey = 5
	MetadataKey_Exif_FNumber      MetadataKey = 6
	MetadataKey_Exif_ISO          MetadataKey = 7
	MetadataKey_Exif_Flash        MetadataKey = 8
	MetadataKey_Exif_WhiteBalance MetadataKey = 9
	MetadataKey_ID                MetadataKey = 10
	MetadataKey_Path              MetadataKey = 11
	MetadataKey_CreationDate      MetadataKey = 12
)

// Enum value maps for MetadataKey.
var (
	MetadataKey_name = map[int32]string{
		0:  "Exif_DateTime",
		1:  "Exif_Make",
		2:  "Exif_Model",
		3:  "Exif_Orientation",
		4:  "Exif_FocalLength",
		5:  "Exif_ExposureTime",
		6:  "Exif_FNumber",
		7:  "Exif_ISO",
		8:  "Exif_Flash",
		9:  "Exif_WhiteBalance",
		10: "ID",
		11: "Path",
		12: "CreationDate",
	}
	MetadataKey_value = map[string]int32{
		"Exif_DateTime":     0,
		"Exif_Make":         1,
		"Exif_Model":        2,
		"Exif_Orientation":  3,
		"Exif_FocalLength":  4,
		"Exif_ExposureTime": 5,
		"Exif_FNumber":      6,
		"Exif_ISO":          7,
		"Exif_Flash":        8,
		"Exif_WhiteBalance": 9,
		"ID":                10,
		"Path":              11,
		"CreationDate":      12,
	}
)

func (x MetadataKey) Enum() *MetadataKey {
	p := new(MetadataKey)
	*p = x
	return p
}

func (x MetadataKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetadataKey) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_grpc_proto_enumTypes[0].Descriptor()
}

func (MetadataKey) Type() protoreflect.EnumType {
	return &file_grpc_grpc_proto_enumTypes[0]
}

func (x MetadataKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetadataKey.Descriptor instead.
func (MetadataKey) EnumDescriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{0}
}

type DirectoryEntry_FileType int32

const (
	DirectoryEntry_DIRECTORY DirectoryEntry_FileType = 0
	DirectoryEntry_MEDIA     DirectoryEntry_FileType = 1
	DirectoryEntry_OTHER     DirectoryEntry_FileType = 2 // symlinks are treated as files
)

// Enum value maps for DirectoryEntry_FileType.
var (
	DirectoryEntry_FileType_name = map[int32]string{
		0: "DIRECTORY",
		1: "MEDIA",
		2: "OTHER",
	}
	DirectoryEntry_FileType_value = map[string]int32{
		"DIRECTORY": 0,
		"MEDIA":     1,
		"OTHER":     2,
	}
)

func (x DirectoryEntry_FileType) Enum() *DirectoryEntry_FileType {
	p := new(DirectoryEntry_FileType)
	*p = x
	return p
}

func (x DirectoryEntry_FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DirectoryEntry_FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_grpc_proto_enumTypes[1].Descriptor()
}

func (DirectoryEntry_FileType) Type() protoreflect.EnumType {
	return &file_grpc_grpc_proto_enumTypes[1]
}

func (x DirectoryEntry_FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DirectoryEntry_FileType.Descriptor instead.
func (DirectoryEntry_FileType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{15, 0}
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_grpc_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_grpc_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_grpc_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FileUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadRequest) Reset() {
	*x = FileUploadRequest{}
	mi := &file_grpc_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadRequest) ProtoMessage() {}

func (x *FileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadRequest.ProtoReflect.Descriptor instead.
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *FileUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileUploadRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type FileUploadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadReply) Reset() {
	*x = FileUploadReply{}
	mi := &file_grpc_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadReply) ProtoMessage() {}

func (x *FileUploadReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadReply.ProtoReflect.Descriptor instead.
func (*FileUploadReply) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *FileUploadReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FileDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloadRequest) Reset() {
	*x = FileDownloadRequest{}
	mi := &file_grpc_grpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadRequest) ProtoMessage() {}

func (x *FileDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadRequest.ProtoReflect.Descriptor instead.
func (*FileDownloadRequest) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *FileDownloadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type FileDownloadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloadReply) Reset() {
	*x = FileDownloadReply{}
	mi := &file_grpc_grpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadReply) ProtoMessage() {}

func (x *FileDownloadReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadReply.ProtoReflect.Descriptor instead.
func (*FileDownloadReply) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *FileDownloadReply) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileDownloadReply) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileDownloadReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Thumbnail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hash
	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// ISO 8601
	CreationTime  string `protobuf:"bytes,3,opt,name=creationTime,proto3" json:"creationTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Thumbnail) Reset() {
	*x = Thumbnail{}
	mi := &file_grpc_grpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thumbnail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thumbnail) ProtoMessage() {}

func (x *Thumbnail) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thumbnail.ProtoReflect.Descriptor instead.
func (*Thumbnail) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{7}
}

func (x *Thumbnail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Thumbnail) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Thumbnail) GetCreationTime() string {
	if x != nil {
		return x.CreationTime
	}
	return ""
}

type ThumbnailsTimestampRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ISO 8601 (e.g., "2025-11-11T13:45:30Z")
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// at most how many thumbnails should be returned
	Count         uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbnailsTimestampRequest) Reset() {
	*x = ThumbnailsTimestampRequest{}
	mi := &file_grpc_grpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailsTimestampRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailsTimestampRequest) ProtoMessage() {}

func (x *ThumbnailsTimestampRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailsTimestampRequest.ProtoReflect.Descriptor instead.
func (*ThumbnailsTimestampRequest) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{8}
}

func (x *ThumbnailsTimestampRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ThumbnailsTimestampRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ThumbnailsTimestampResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Thumbnails    []*Thumbnail           `protobuf:"bytes,2,rep,name=thumbnails,proto3" json:"thumbnails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbnailsTimestampResponse) Reset() {
	*x = ThumbnailsTimestampResponse{}
	mi := &file_grpc_grpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailsTimestampResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailsTimestampResponse) ProtoMessage() {}

func (x *ThumbnailsTimestampResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailsTimestampResponse.ProtoReflect.Descriptor instead.
func (*ThumbnailsTimestampResponse) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{9}
}

func (x *ThumbnailsTimestampResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ThumbnailsTimestampResponse) GetThumbnails() []*Thumbnail {
	if x != nil {
		return x.Thumbnails
	}
	return nil
}

type GetMediaItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaItemRequest) Reset() {
	*x = GetMediaItemRequest{}
	mi := &file_grpc_grpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaItemRequest) ProtoMessage() {}

func (x *GetMediaItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaItemRequest.ProtoReflect.Descriptor instead.
func (*GetMediaItemRequest) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{10}
}

func (x *GetMediaItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MediaItem struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreationTime string                 `protobuf:"bytes,2,opt,name=creationTime,proto3" json:"creationTime,omitempty"`
	Content      []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// Optional. Rooted at `mediadir` directory, without a leading `/`.
	Path          string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItem) Reset() {
	*x = MediaItem{}
	mi := &file_grpc_grpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItem) ProtoMessage() {}

func (x *MediaItem) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItem.ProtoReflect.Descriptor instead.
func (*MediaItem) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{11}
}

func (x *MediaItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaItem) GetCreationTime() string {
	if x != nil {
		return x.CreationTime
	}
	return ""
}

func (x *MediaItem) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MediaItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetMediaItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	MediaItem     *MediaItem             `protobuf:"bytes,2,opt,name=mediaItem,proto3" json:"mediaItem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaItemResponse) Reset() {
	*x = GetMediaItemResponse{}
	mi := &file_grpc_grpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaItemResponse) ProtoMessage() {}

func (x *GetMediaItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaItemResponse.ProtoReflect.Descriptor instead.
func (*GetMediaItemResponse) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{12}
}

func (x *GetMediaItemResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetMediaItemResponse) GetMediaItem() *MediaItem {
	if x != nil {
		return x.MediaItem
	}
	return nil
}

type GetFileListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileListRequest) Reset() {
	*x = GetFileListRequest{}
	mi := &file_grpc_grpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileListRequest) ProtoMessage() {}

func (x *GetFileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileListRequest.ProtoReflect.Descriptor instead.
func (*GetFileListRequest) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{13}
}

func (x *GetFileListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetFileListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Entries       []*DirectoryEntry      `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileListResponse) Reset() {
	*x = GetFileListResponse{}
	mi := &file_grpc_grpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileListResponse) ProtoMessage() {}

func (x *GetFileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileListResponse.ProtoReflect.Descriptor instead.
func (*GetFileListResponse) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{14}
}

func (x *GetFileListResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetFileListResponse) GetEntries() []*DirectoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DirectoryEntry struct {
	state protoimpl.MessageState  `protogen:"open.v1"`
	Type  DirectoryEntry_FileType `protobuf:"varint,1,opt,name=type,proto3,enum=DirectoryEntry_FileType" json:"type,omitempty"`
	Name  string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// for media files, currently only images
	Media         *TimelineEntry `protobuf:"bytes,3,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectoryEntry) Reset() {
	*x = DirectoryEntry{}
	mi := &file_grpc_grpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryEntry) ProtoMessage() {}

func (x *DirectoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryEntry.ProtoReflect.Descriptor instead.
func (*DirectoryEntry) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{15}
}

func (x *DirectoryEntry) GetType() DirectoryEntry_FileType {
	if x != nil {
		return x.Type
	}
	return DirectoryEntry_DIRECTORY
}

func (x *DirectoryEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirectoryEntry) GetMedia() *TimelineEntry {
	if x != nil {
		return x.Media
	}
	return nil
}

type TimelineEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hash
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ISO 8601
	CreationTime  string `protobuf:"bytes,2,opt,name=creationTime,proto3" json:"creationTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineEntry) Reset() {
	*x = TimelineEntry{}
	mi := &file_grpc_grpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineEntry) ProtoMessage() {}

func (x *TimelineEntry) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineEntry.ProtoReflect.Descriptor instead.
func (*TimelineEntry) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{16}
}

func (x *TimelineEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TimelineEntry) GetCreationTime() string {
	if x != nil {
		return x.CreationTime
	}
	return ""
}

type TimelineEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineEntriesRequest) Reset() {
	*x = TimelineEntriesRequest{}
	mi := &file_grpc_grpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineEntriesRequest) ProtoMessage() {}

func (x *TimelineEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineEntriesRequest.ProtoReflect.Descriptor instead.
func (*TimelineEntriesRequest) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{17}
}

type TimelineEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Entries       []*TimelineEntry       `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineEntriesResponse) Reset() {
	*x = TimelineEntriesResponse{}
	mi := &file_grpc_grpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineEntriesResponse) ProtoMessage() {}

func (x *TimelineEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineEntriesResponse.ProtoReflect.Descriptor instead.
func (*TimelineEntriesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{18}
}

func (x *TimelineEntriesResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TimelineEntriesResponse) GetEntries() []*TimelineEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FullMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullMetadataRequest) Reset() {
	*x = FullMetadataRequest{}
	mi := &file_grpc_grpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullMetadataRequest) ProtoMessage() {}

func (x *FullMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullMetadataRequest.ProtoReflect.Descriptor instead.
func (*FullMetadataRequest) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{19}
}

func (x *FullMetadataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FullMetadataReply struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// key(int32) is MetadataKey!
	Values        map[int32]string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullMetadataReply) Reset() {
	*x = FullMetadataReply{}
	mi := &file_grpc_grpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullMetadataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullMetadataReply) ProtoMessage() {}

func (x *FullMetadataReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullMetadataReply.ProtoReflect.Descriptor instead.
func (*FullMetadataReply) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{20}
}

func (x *FullMetadataReply) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *FullMetadataReply) GetValues() map[int32]string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_grpc_grpc_proto protoreflect.FileDescriptor

const file_grpc_grpc_proto_rawDesc = "" +
	"\n" +
	"\x0fgrpc/grpc.proto\"6\n" +
	"\x06Status\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"I\n" +
	"\x11FileUploadRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"+\n" +
	"\x0fFileUploadReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"1\n" +
	"\x13FileDownloadRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"c\n" +
	"\x11FileDownloadReply\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"Y\n" +
	"\tThumbnail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\"\n" +
	"\fcreationTime\x18\x03 \x01(\tR\fcreationTime\"P\n" +
	"\x1aThumbnailsTimestampRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"j\n" +
	"\x1bThumbnailsTimestampResponse\x12\x1f\n" +
	"\x06status\x18\x01 \x01(\v2\a.StatusR\x06status\x12*\n" +
	"\n" +
	"thumbnails\x18\x02 \x03(\v2\n" +
	".ThumbnailR\n" +
	"thumbnails\"%\n" +
	"\x13GetMediaItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"m\n" +
	"\tMediaItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fcreationTime\x18\x02 \x01(\tR\fcreationTime\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"a\n" +
	"\x14GetMediaItemResponse\x12\x1f\n" +
	"\x06status\x18\x01 \x01(\v2\a.StatusR\x06status\x12(\n" +
	"\tmediaItem\x18\x02 \x01(\v2\n" +
	".MediaItemR\tmediaItem\"(\n" +
	"\x12GetFileListRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"a\n" +
	"\x13GetFileListResponse\x12\x1f\n" +
	"\x06status\x18\x01 \x01(\v2\a.StatusR\x06status\x12)\n" +
	"\aentries\x18\x02 \x03(\v2\x0f.DirectoryEntryR\aentries\"\xa9\x01\n" +
	"\x0eDirectoryEntry\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.DirectoryEntry.FileTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x05media\x18\x03 \x01(\v2\x0e.TimelineEntryR\x05media\"/\n" +
	"\bFileType\x12\r\n" +
	"\tDIRECTORY\x10\x00\x12\t\n" +
	"\x05MEDIA\x10\x01\x12\t\n" +
	"\x05OTHER\x10\x02\"C\n" +
	"\rTimelineEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fcreationTime\x18\x02 \x01(\tR\fcreationTime\"\x18\n" +
	"\x16TimelineEntriesRequest\"d\n" +
	"\x17TimelineEntriesResponse\x12\x1f\n" +
	"\x06status\x18\x01 \x01(\v2\a.StatusR\x06status\x12(\n" +
	"\aentries\x18\x02 \x03(\v2\x0e.TimelineEntryR\aentries\"%\n" +
	"\x13FullMetadataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa7\x01\n" +
	"\x11FullMetadataReply\x12\x1f\n" +
	"\x06status\x18\x01 \x01(\v2\a.StatusR\x06status\x126\n" +
	"\x06values\x18\x02 \x03(\v2\x1e.FullMetadataReply.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xed\x01\n" +
	"\vMetadataKey\x12\x11\n" +
	"\rExif_DateTime\x10\x00\x12\r\n" +
	"\tExif_Make\x10\x01\x12\x0e\n" +
	"\n" +
	"Exif_Model\x10\x02\x12\x14\n" +
	"\x10Exif_Orientation\x10\x03\x12\x14\n" +
	"\x10Exif_FocalLength\x10\x04\x12\x15\n" +
	"\x11Exif_ExposureTime\x10\x05\x12\x10\n" +
	"\fExif_FNumber\x10\x06\x12\f\n" +
	"\bExif_ISO\x10\a\x12\x0e\n" +
	"\n" +
	"Exif_Flash\x10\b\x12\x15\n" +
	"\x11Exif_WhiteBalance\x10\t\x12\x06\n" +
	"\x02ID\x10\n" +
	"\x12\b\n" +
	"\x04Path\x10\v\x12\x10\n" +
	"\fCreationDate\x10\f2\x80\x05\n" +
	"\aMigawka\x12(\n" +
	"\bSayHello\x12\r.HelloRequest\x1a\v.HelloReply\"\x00\x122\n" +
	"\n" +
	"UploadFile\x12\x12.FileUploadRequest\x1a\x10.FileUploadReply\x128\n" +
	"\fDownloadFile\x12\x14.FileDownloadRequest\x1a\x12.FileDownloadReply\x12Y\n" +
	"\x1cGetThumbnailsBeforeTimestamp\x12\x1b.ThumbnailsTimestampRequest\x1a\x1c.ThumbnailsTimestampResponse\x12G\n" +
	"\x12GetTimelineEntries\x12\x17.TimelineEntriesRequest\x1a\x18.TimelineEntriesResponse\x12D\n" +
	"\x15GetOptimizedMediaItem\x12\x14.GetMediaItemRequest\x1a\x15.GetMediaItemResponse\x12;\n" +
	"\fGetThumbnail\x12\x14.GetMediaItemRequest\x1a\x15.GetMediaItemResponse\x12?\n" +
	"\x10GetFullMediaItem\x12\x14.GetMediaItemRequest\x1a\x15.GetMediaItemResponse\x128\n" +
	"\vGetFileList\x12\x13.GetFileListRequest\x1a\x14.GetFileListResponse\x12;\n" +
	"\x0fGetFullMetadata\x12\x14.FullMetadataRequest\x1a\x12.FullMetadataReplyB,\n" +
	"\x13xyz.jdubiel.migawkaP\x01Z\x13migawka-server/grpcb\x06proto3"

var (
	file_grpc_grpc_proto_rawDescOnce sync.Once
	file_grpc_grpc_proto_rawDescData []byte
)

func file_grpc_grpc_proto_rawDescGZIP() []byte {
	file_grpc_grpc_proto_rawDescOnce.Do(func() {
		file_grpc_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_grpc_proto_rawDesc), len(file_grpc_grpc_proto_rawDesc)))
	})
	return file_grpc_grpc_proto_rawDescData
}

var file_grpc_grpc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grpc_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_grpc_grpc_proto_goTypes = []any{
	(MetadataKey)(0),                    // 0: MetadataKey
	(DirectoryEntry_FileType)(0),        // 1: DirectoryEntry.FileType
	(*Status)(nil),                      // 2: Status
	(*HelloRequest)(nil),                // 3: HelloRequest
	(*HelloReply)(nil),                  // 4: HelloReply
	(*FileUploadRequest)(nil),           // 5: FileUploadRequest
	(*FileUploadReply)(nil),             // 6: FileUploadReply
	(*FileDownloadRequest)(nil),         // 7: FileDownloadRequest
	(*FileDownloadReply)(nil),           // 8: FileDownloadReply
	(*Thumbnail)(nil),                   // 9: Thumbnail
	(*ThumbnailsTimestampRequest)(nil),  // 10: ThumbnailsTimestampRequest
	(*ThumbnailsTimestampResponse)(nil), // 11: ThumbnailsTimestampResponse
	(*GetMediaItemRequest)(nil),         // 12: GetMediaItemRequest
	(*MediaItem)(nil),                   // 13: MediaItem
	(*GetMediaItemResponse)(nil),        // 14: GetMediaItemResponse
	(*GetFileListRequest)(nil),          // 15: GetFileListRequest
	(*GetFileListResponse)(nil),         // 16: GetFileListResponse
	(*DirectoryEntry)(nil),              // 17: DirectoryEntry
	(*TimelineEntry)(nil),               // 18: TimelineEntry
	(*TimelineEntriesRequest)(nil),      // 19: TimelineEntriesRequest
	(*TimelineEntriesResponse)(nil),     // 20: TimelineEntriesResponse
	(*FullMetadataRequest)(nil),         // 21: FullMetadataRequest
	(*FullMetadataReply)(nil),           // 22: FullMetadataReply
	nil,                                 // 23: FullMetadataReply.ValuesEntry
}
var file_grpc_grpc_proto_depIdxs = []int32{
	2,  // 0: ThumbnailsTimestampResponse.status:type_name -> Status
	9,  // 1: ThumbnailsTimestampResponse.thumbnails:type_name -> Thumbnail
	2,  // 2: GetMediaItemResponse.status:type_name -> Status
	13, // 3: GetMediaItemResponse.mediaItem:type_name -> MediaItem
	2,  // 4: GetFileListResponse.status:type_name -> Status
	17, // 5: GetFileListResponse.entries:type_name -> DirectoryEntry
	1,  // 6: DirectoryEntry.type:type_name -> DirectoryEntry.FileType
	18, // 7: DirectoryEntry.media:type_name -> TimelineEntry
	2,  // 8: TimelineEntriesResponse.status:type_name -> Status
	18, // 9: TimelineEntriesResponse.entries:type_name -> TimelineEntry
	2,  // 10: FullMetadataReply.status:type_name -> Status
	23, // 11: FullMetadataReply.values:type_name -> FullMetadataReply.ValuesEntry
	3,  // 12: Migawka.SayHello:input_type -> HelloRequest
	5,  // 13: Migawka.UploadFile:input_type -> FileUploadRequest
	7,  // 14: Migawka.DownloadFile:input_type -> FileDownloadRequest
	10, // 15: Migawka.GetThumbnailsBeforeTimestamp:input_type -> ThumbnailsTimestampRequest
	19, // 16: Migawka.GetTimelineEntries:input_type -> TimelineEntriesRequest
	12, // 17: Migawka.GetOptimizedMediaItem:input_type -> GetMediaItemRequest
	12, // 18: Migawka.GetThumbnail:input_type -> GetMediaItemRequest
	12, // 19: Migawka.GetFullMediaItem:input_type -> GetMediaItemRequest
	15, // 20: Migawka.GetFileList:input_type -> GetFileListRequest
	21, // 21: Migawka.GetFullMetadata:input_type -> FullMetadataRequest
	4,  // 22: Migawka.SayHello:output_type -> HelloReply
	6,  // 23: Migawka.UploadFile:output_type -> FileUploadReply
	8,  // 24: Migawka.DownloadFile:output_type -> FileDownloadReply
	11, // 25: Migawka.GetThumbnailsBeforeTimestamp:output_type -> ThumbnailsTimestampResponse
	20, // 26: Migawka.GetTimelineEntries:output_type -> TimelineEntriesResponse
	14, // 27: Migawka.GetOptimizedMediaItem:output_type -> GetMediaItemResponse
	14, // 28: Migawka.GetThumbnail:output_type -> GetMediaItemResponse
	14, // 29: Migawka.GetFullMediaItem:output_type -> GetMediaItemResponse
	16, // 30: Migawka.GetFileList:output_type -> GetFileListResponse
	22, // 31: Migawka.GetFullMetadata:output_type -> FullMetadataReply
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_grpc_grpc_proto_init() }
func file_grpc_grpc_proto_init() {
	if File_grpc_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_grpc_proto_rawDesc), len(file_grpc_grpc_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_grpc_proto_goTypes,
		DependencyIndexes: file_grpc_grpc_proto_depIdxs,
		EnumInfos:         file_grpc_grpc_proto_enumTypes,
		MessageInfos:      file_grpc_grpc_proto_msgTypes,
	}.Build()
	File_grpc_grpc_proto = out.File
	file_grpc_grpc_proto_goTypes = nil
	file_grpc_grpc_proto_depIdxs = nil
}
