// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: grpc/grpc.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Migawka_SayHello_FullMethodName                     = "/Migawka/SayHello"
	Migawka_UploadFile_FullMethodName                   = "/Migawka/UploadFile"
	Migawka_DownloadFile_FullMethodName                 = "/Migawka/DownloadFile"
	Migawka_GetThumbnailsBeforeTimestamp_FullMethodName = "/Migawka/GetThumbnailsBeforeTimestamp"
	Migawka_GetTimelineEntries_FullMethodName           = "/Migawka/GetTimelineEntries"
	Migawka_GetOptimizedMediaItem_FullMethodName        = "/Migawka/GetOptimizedMediaItem"
	Migawka_GetThumbnail_FullMethodName                 = "/Migawka/GetThumbnail"
	Migawka_GetFullMediaItem_FullMethodName             = "/Migawka/GetFullMediaItem"
	Migawka_GetFileListPage_FullMethodName              = "/Migawka/GetFileListPage"
)

// MigawkaClient is the client API for Migawka service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type MigawkaClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	UploadFile(ctx context.Context, in *FileUploadRequest, opts ...grpc.CallOption) (*FileUploadReply, error)
	DownloadFile(ctx context.Context, in *FileDownloadRequest, opts ...grpc.CallOption) (*FileDownloadReply, error)
	GetThumbnailsBeforeTimestamp(ctx context.Context, in *ThumbnailsTimestampRequest, opts ...grpc.CallOption) (*ThumbnailsTimestampResponse, error)
	GetTimelineEntries(ctx context.Context, in *TimelineEntriesRequest, opts ...grpc.CallOption) (*TimelineEntriesResponse, error)
	GetOptimizedMediaItem(ctx context.Context, in *GetMediaItemRequest, opts ...grpc.CallOption) (*GetMediaItemResponse, error)
	GetThumbnail(ctx context.Context, in *GetMediaItemRequest, opts ...grpc.CallOption) (*GetMediaItemResponse, error)
	GetFullMediaItem(ctx context.Context, in *GetMediaItemRequest, opts ...grpc.CallOption) (*GetMediaItemResponse, error)
	GetFileListPage(ctx context.Context, in *GetFileListPageRequest, opts ...grpc.CallOption) (*GetFileListPageResponse, error)
}

type migawkaClient struct {
	cc grpc.ClientConnInterface
}

func NewMigawkaClient(cc grpc.ClientConnInterface) MigawkaClient {
	return &migawkaClient{cc}
}

func (c *migawkaClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Migawka_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migawkaClient) UploadFile(ctx context.Context, in *FileUploadRequest, opts ...grpc.CallOption) (*FileUploadReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileUploadReply)
	err := c.cc.Invoke(ctx, Migawka_UploadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migawkaClient) DownloadFile(ctx context.Context, in *FileDownloadRequest, opts ...grpc.CallOption) (*FileDownloadReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileDownloadReply)
	err := c.cc.Invoke(ctx, Migawka_DownloadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migawkaClient) GetThumbnailsBeforeTimestamp(ctx context.Context, in *ThumbnailsTimestampRequest, opts ...grpc.CallOption) (*ThumbnailsTimestampResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThumbnailsTimestampResponse)
	err := c.cc.Invoke(ctx, Migawka_GetThumbnailsBeforeTimestamp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migawkaClient) GetTimelineEntries(ctx context.Context, in *TimelineEntriesRequest, opts ...grpc.CallOption) (*TimelineEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimelineEntriesResponse)
	err := c.cc.Invoke(ctx, Migawka_GetTimelineEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migawkaClient) GetOptimizedMediaItem(ctx context.Context, in *GetMediaItemRequest, opts ...grpc.CallOption) (*GetMediaItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMediaItemResponse)
	err := c.cc.Invoke(ctx, Migawka_GetOptimizedMediaItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migawkaClient) GetThumbnail(ctx context.Context, in *GetMediaItemRequest, opts ...grpc.CallOption) (*GetMediaItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMediaItemResponse)
	err := c.cc.Invoke(ctx, Migawka_GetThumbnail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migawkaClient) GetFullMediaItem(ctx context.Context, in *GetMediaItemRequest, opts ...grpc.CallOption) (*GetMediaItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMediaItemResponse)
	err := c.cc.Invoke(ctx, Migawka_GetFullMediaItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migawkaClient) GetFileListPage(ctx context.Context, in *GetFileListPageRequest, opts ...grpc.CallOption) (*GetFileListPageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileListPageResponse)
	err := c.cc.Invoke(ctx, Migawka_GetFileListPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MigawkaServer is the server API for Migawka service.
// All implementations must embed UnimplementedMigawkaServer
// for forward compatibility.
//
// The greeting service definition.
type MigawkaServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	UploadFile(context.Context, *FileUploadRequest) (*FileUploadReply, error)
	DownloadFile(context.Context, *FileDownloadRequest) (*FileDownloadReply, error)
	GetThumbnailsBeforeTimestamp(context.Context, *ThumbnailsTimestampRequest) (*ThumbnailsTimestampResponse, error)
	GetTimelineEntries(context.Context, *TimelineEntriesRequest) (*TimelineEntriesResponse, error)
	GetOptimizedMediaItem(context.Context, *GetMediaItemRequest) (*GetMediaItemResponse, error)
	GetThumbnail(context.Context, *GetMediaItemRequest) (*GetMediaItemResponse, error)
	GetFullMediaItem(context.Context, *GetMediaItemRequest) (*GetMediaItemResponse, error)
	GetFileListPage(context.Context, *GetFileListPageRequest) (*GetFileListPageResponse, error)
	mustEmbedUnimplementedMigawkaServer()
}

// UnimplementedMigawkaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMigawkaServer struct{}

func (UnimplementedMigawkaServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedMigawkaServer) UploadFile(context.Context, *FileUploadRequest) (*FileUploadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedMigawkaServer) DownloadFile(context.Context, *FileDownloadRequest) (*FileDownloadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedMigawkaServer) GetThumbnailsBeforeTimestamp(context.Context, *ThumbnailsTimestampRequest) (*ThumbnailsTimestampResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThumbnailsBeforeTimestamp not implemented")
}
func (UnimplementedMigawkaServer) GetTimelineEntries(context.Context, *TimelineEntriesRequest) (*TimelineEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimelineEntries not implemented")
}
func (UnimplementedMigawkaServer) GetOptimizedMediaItem(context.Context, *GetMediaItemRequest) (*GetMediaItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOptimizedMediaItem not implemented")
}
func (UnimplementedMigawkaServer) GetThumbnail(context.Context, *GetMediaItemRequest) (*GetMediaItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThumbnail not implemented")
}
func (UnimplementedMigawkaServer) GetFullMediaItem(context.Context, *GetMediaItemRequest) (*GetMediaItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFullMediaItem not implemented")
}
func (UnimplementedMigawkaServer) GetFileListPage(context.Context, *GetFileListPageRequest) (*GetFileListPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileListPage not implemented")
}
func (UnimplementedMigawkaServer) mustEmbedUnimplementedMigawkaServer() {}
func (UnimplementedMigawkaServer) testEmbeddedByValue()                 {}

// UnsafeMigawkaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MigawkaServer will
// result in compilation errors.
type UnsafeMigawkaServer interface {
	mustEmbedUnimplementedMigawkaServer()
}

func RegisterMigawkaServer(s grpc.ServiceRegistrar, srv MigawkaServer) {
	// If the following call pancis, it indicates UnimplementedMigawkaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Migawka_ServiceDesc, srv)
}

func _Migawka_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigawkaServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migawka_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigawkaServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migawka_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigawkaServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migawka_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigawkaServer).UploadFile(ctx, req.(*FileUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migawka_DownloadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigawkaServer).DownloadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migawka_DownloadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigawkaServer).DownloadFile(ctx, req.(*FileDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migawka_GetThumbnailsBeforeTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThumbnailsTimestampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigawkaServer).GetThumbnailsBeforeTimestamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migawka_GetThumbnailsBeforeTimestamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigawkaServer).GetThumbnailsBeforeTimestamp(ctx, req.(*ThumbnailsTimestampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migawka_GetTimelineEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimelineEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigawkaServer).GetTimelineEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migawka_GetTimelineEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigawkaServer).GetTimelineEntries(ctx, req.(*TimelineEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migawka_GetOptimizedMediaItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMediaItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigawkaServer).GetOptimizedMediaItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migawka_GetOptimizedMediaItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigawkaServer).GetOptimizedMediaItem(ctx, req.(*GetMediaItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migawka_GetThumbnail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMediaItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigawkaServer).GetThumbnail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migawka_GetThumbnail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigawkaServer).GetThumbnail(ctx, req.(*GetMediaItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migawka_GetFullMediaItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMediaItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigawkaServer).GetFullMediaItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migawka_GetFullMediaItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigawkaServer).GetFullMediaItem(ctx, req.(*GetMediaItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migawka_GetFileListPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileListPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigawkaServer).GetFileListPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migawka_GetFileListPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigawkaServer).GetFileListPage(ctx, req.(*GetFileListPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Migawka_ServiceDesc is the grpc.ServiceDesc for Migawka service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Migawka_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Migawka",
	HandlerType: (*MigawkaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Migawka_SayHello_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _Migawka_UploadFile_Handler,
		},
		{
			MethodName: "DownloadFile",
			Handler:    _Migawka_DownloadFile_Handler,
		},
		{
			MethodName: "GetThumbnailsBeforeTimestamp",
			Handler:    _Migawka_GetThumbnailsBeforeTimestamp_Handler,
		},
		{
			MethodName: "GetTimelineEntries",
			Handler:    _Migawka_GetTimelineEntries_Handler,
		},
		{
			MethodName: "GetOptimizedMediaItem",
			Handler:    _Migawka_GetOptimizedMediaItem_Handler,
		},
		{
			MethodName: "GetThumbnail",
			Handler:    _Migawka_GetThumbnail_Handler,
		},
		{
			MethodName: "GetFullMediaItem",
			Handler:    _Migawka_GetFullMediaItem_Handler,
		},
		{
			MethodName: "GetFileListPage",
			Handler:    _Migawka_GetFileListPage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/grpc.proto",
}
