// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: grpc/grpc.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DirectoryEntry_FileType int32

const (
	DirectoryEntry_DIRECTORY DirectoryEntry_FileType = 0
	DirectoryEntry_MEDIA     DirectoryEntry_FileType = 1
	DirectoryEntry_OTHER     DirectoryEntry_FileType = 2 // symlinks are treated as files
)

// Enum value maps for DirectoryEntry_FileType.
var (
	DirectoryEntry_FileType_name = map[int32]string{
		0: "DIRECTORY",
		1: "MEDIA",
		2: "OTHER",
	}
	DirectoryEntry_FileType_value = map[string]int32{
		"DIRECTORY": 0,
		"MEDIA":     1,
		"OTHER":     2,
	}
)

func (x DirectoryEntry_FileType) Enum() *DirectoryEntry_FileType {
	p := new(DirectoryEntry_FileType)
	*p = x
	return p
}

func (x DirectoryEntry_FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DirectoryEntry_FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_grpc_proto_enumTypes[0].Descriptor()
}

func (DirectoryEntry_FileType) Type() protoreflect.EnumType {
	return &file_grpc_grpc_proto_enumTypes[0]
}

func (x DirectoryEntry_FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DirectoryEntry_FileType.Descriptor instead.
func (DirectoryEntry_FileType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{15, 0}
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_grpc_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_grpc_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_grpc_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FileUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadRequest) Reset() {
	*x = FileUploadRequest{}
	mi := &file_grpc_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadRequest) ProtoMessage() {}

func (x *FileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadRequest.ProtoReflect.Descriptor instead.
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *FileUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileUploadRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type FileUploadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadReply) Reset() {
	*x = FileUploadReply{}
	mi := &file_grpc_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadReply) ProtoMessage() {}

func (x *FileUploadReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadReply.ProtoReflect.Descriptor instead.
func (*FileUploadReply) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *FileUploadReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FileDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloadRequest) Reset() {
	*x = FileDownloadRequest{}
	mi := &file_grpc_grpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadRequest) ProtoMessage() {}

func (x *FileDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadRequest.ProtoReflect.Descriptor instead.
func (*FileDownloadRequest) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *FileDownloadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type FileDownloadReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloadReply) Reset() {
	*x = FileDownloadReply{}
	mi := &file_grpc_grpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadReply) ProtoMessage() {}

func (x *FileDownloadReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadReply.ProtoReflect.Descriptor instead.
func (*FileDownloadReply) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *FileDownloadReply) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileDownloadReply) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileDownloadReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Thumbnail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hash
	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// ISO 8601
	CreationTime  string `protobuf:"bytes,3,opt,name=creationTime,proto3" json:"creationTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Thumbnail) Reset() {
	*x = Thumbnail{}
	mi := &file_grpc_grpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thumbnail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thumbnail) ProtoMessage() {}

func (x *Thumbnail) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thumbnail.ProtoReflect.Descriptor instead.
func (*Thumbnail) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{7}
}

func (x *Thumbnail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Thumbnail) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Thumbnail) GetCreationTime() string {
	if x != nil {
		return x.CreationTime
	}
	return ""
}

type ThumbnailsTimestampRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ISO 8601 (e.g., "2025-11-11T13:45:30Z")
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// at most how many thumbnails should be returned
	Count         uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbnailsTimestampRequest) Reset() {
	*x = ThumbnailsTimestampRequest{}
	mi := &file_grpc_grpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailsTimestampRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailsTimestampRequest) ProtoMessage() {}

func (x *ThumbnailsTimestampRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailsTimestampRequest.ProtoReflect.Descriptor instead.
func (*ThumbnailsTimestampRequest) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{8}
}

func (x *ThumbnailsTimestampRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ThumbnailsTimestampRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ThumbnailsTimestampResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Thumbnails    []*Thumbnail           `protobuf:"bytes,2,rep,name=thumbnails,proto3" json:"thumbnails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbnailsTimestampResponse) Reset() {
	*x = ThumbnailsTimestampResponse{}
	mi := &file_grpc_grpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailsTimestampResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailsTimestampResponse) ProtoMessage() {}

func (x *ThumbnailsTimestampResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailsTimestampResponse.ProtoReflect.Descriptor instead.
func (*ThumbnailsTimestampResponse) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{9}
}

func (x *ThumbnailsTimestampResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ThumbnailsTimestampResponse) GetThumbnails() []*Thumbnail {
	if x != nil {
		return x.Thumbnails
	}
	return nil
}

type GetMediaItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaItemRequest) Reset() {
	*x = GetMediaItemRequest{}
	mi := &file_grpc_grpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaItemRequest) ProtoMessage() {}

func (x *GetMediaItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaItemRequest.ProtoReflect.Descriptor instead.
func (*GetMediaItemRequest) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{10}
}

func (x *GetMediaItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MediaItem struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreationTime string                 `protobuf:"bytes,2,opt,name=creationTime,proto3" json:"creationTime,omitempty"`
	Content      []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// Optional. Rooted at `mediadir` directory, without a leading `/`.
	Path          string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItem) Reset() {
	*x = MediaItem{}
	mi := &file_grpc_grpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItem) ProtoMessage() {}

func (x *MediaItem) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItem.ProtoReflect.Descriptor instead.
func (*MediaItem) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{11}
}

func (x *MediaItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaItem) GetCreationTime() string {
	if x != nil {
		return x.CreationTime
	}
	return ""
}

func (x *MediaItem) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MediaItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetMediaItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	MediaItem     *MediaItem             `protobuf:"bytes,2,opt,name=mediaItem,proto3" json:"mediaItem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaItemResponse) Reset() {
	*x = GetMediaItemResponse{}
	mi := &file_grpc_grpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaItemResponse) ProtoMessage() {}

func (x *GetMediaItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaItemResponse.ProtoReflect.Descriptor instead.
func (*GetMediaItemResponse) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{12}
}

func (x *GetMediaItemResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetMediaItemResponse) GetMediaItem() *MediaItem {
	if x != nil {
		return x.MediaItem
	}
	return nil
}

type GetFileListPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	PageNumber    uint32                 `protobuf:"varint,2,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileListPageRequest) Reset() {
	*x = GetFileListPageRequest{}
	mi := &file_grpc_grpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileListPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileListPageRequest) ProtoMessage() {}

func (x *GetFileListPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileListPageRequest.ProtoReflect.Descriptor instead.
func (*GetFileListPageRequest) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{13}
}

func (x *GetFileListPageRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetFileListPageRequest) GetPageNumber() uint32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *GetFileListPageRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetFileListPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Entries       []*DirectoryEntry      `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileListPageResponse) Reset() {
	*x = GetFileListPageResponse{}
	mi := &file_grpc_grpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileListPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileListPageResponse) ProtoMessage() {}

func (x *GetFileListPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileListPageResponse.ProtoReflect.Descriptor instead.
func (*GetFileListPageResponse) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{14}
}

func (x *GetFileListPageResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetFileListPageResponse) GetEntries() []*DirectoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DirectoryEntry struct {
	state protoimpl.MessageState  `protogen:"open.v1"`
	Type  DirectoryEntry_FileType `protobuf:"varint,1,opt,name=type,proto3,enum=DirectoryEntry_FileType" json:"type,omitempty"`
	Name  string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// for image files
	Thumbnail     *Thumbnail `protobuf:"bytes,3,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectoryEntry) Reset() {
	*x = DirectoryEntry{}
	mi := &file_grpc_grpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryEntry) ProtoMessage() {}

func (x *DirectoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryEntry.ProtoReflect.Descriptor instead.
func (*DirectoryEntry) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{15}
}

func (x *DirectoryEntry) GetType() DirectoryEntry_FileType {
	if x != nil {
		return x.Type
	}
	return DirectoryEntry_DIRECTORY
}

func (x *DirectoryEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirectoryEntry) GetThumbnail() *Thumbnail {
	if x != nil {
		return x.Thumbnail
	}
	return nil
}

type TimelineEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hash
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ISO 8601
	CreationTime  string `protobuf:"bytes,2,opt,name=creationTime,proto3" json:"creationTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineEntry) Reset() {
	*x = TimelineEntry{}
	mi := &file_grpc_grpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineEntry) ProtoMessage() {}

func (x *TimelineEntry) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineEntry.ProtoReflect.Descriptor instead.
func (*TimelineEntry) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{16}
}

func (x *TimelineEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TimelineEntry) GetCreationTime() string {
	if x != nil {
		return x.CreationTime
	}
	return ""
}

type TimelineEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineEntriesRequest) Reset() {
	*x = TimelineEntriesRequest{}
	mi := &file_grpc_grpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineEntriesRequest) ProtoMessage() {}

func (x *TimelineEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineEntriesRequest.ProtoReflect.Descriptor instead.
func (*TimelineEntriesRequest) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{17}
}

type TimelineEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Entries       []*TimelineEntry       `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineEntriesResponse) Reset() {
	*x = TimelineEntriesResponse{}
	mi := &file_grpc_grpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineEntriesResponse) ProtoMessage() {}

func (x *TimelineEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_grpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineEntriesResponse.ProtoReflect.Descriptor instead.
func (*TimelineEntriesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_grpc_proto_rawDescGZIP(), []int{18}
}

func (x *TimelineEntriesResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TimelineEntriesResponse) GetEntries() []*TimelineEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_grpc_grpc_proto protoreflect.FileDescriptor

const file_grpc_grpc_proto_rawDesc = "" +
	"\n" +
	"\x0fgrpc/grpc.proto\"6\n" +
	"\x06Status\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"I\n" +
	"\x11FileUploadRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"+\n" +
	"\x0fFileUploadReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"1\n" +
	"\x13FileDownloadRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"c\n" +
	"\x11FileDownloadReply\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"Y\n" +
	"\tThumbnail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\"\n" +
	"\fcreationTime\x18\x03 \x01(\tR\fcreationTime\"P\n" +
	"\x1aThumbnailsTimestampRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"j\n" +
	"\x1bThumbnailsTimestampResponse\x12\x1f\n" +
	"\x06status\x18\x01 \x01(\v2\a.StatusR\x06status\x12*\n" +
	"\n" +
	"thumbnails\x18\x02 \x03(\v2\n" +
	".ThumbnailR\n" +
	"thumbnails\"%\n" +
	"\x13GetMediaItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"m\n" +
	"\tMediaItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fcreationTime\x18\x02 \x01(\tR\fcreationTime\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"a\n" +
	"\x14GetMediaItemResponse\x12\x1f\n" +
	"\x06status\x18\x01 \x01(\v2\a.StatusR\x06status\x12(\n" +
	"\tmediaItem\x18\x02 \x01(\v2\n" +
	".MediaItemR\tmediaItem\"h\n" +
	"\x16GetFileListPageRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1e\n" +
	"\n" +
	"pageNumber\x18\x02 \x01(\rR\n" +
	"pageNumber\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\rR\bpageSize\"e\n" +
	"\x17GetFileListPageResponse\x12\x1f\n" +
	"\x06status\x18\x01 \x01(\v2\a.StatusR\x06status\x12)\n" +
	"\aentries\x18\x02 \x03(\v2\x0f.DirectoryEntryR\aentries\"\xad\x01\n" +
	"\x0eDirectoryEntry\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.DirectoryEntry.FileTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\tthumbnail\x18\x03 \x01(\v2\n" +
	".ThumbnailR\tthumbnail\"/\n" +
	"\bFileType\x12\r\n" +
	"\tDIRECTORY\x10\x00\x12\t\n" +
	"\x05MEDIA\x10\x01\x12\t\n" +
	"\x05OTHER\x10\x02\"C\n" +
	"\rTimelineEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fcreationTime\x18\x02 \x01(\tR\fcreationTime\"\x18\n" +
	"\x16TimelineEntriesRequest\"d\n" +
	"\x17TimelineEntriesResponse\x12\x1f\n" +
	"\x06status\x18\x01 \x01(\v2\a.StatusR\x06status\x12(\n" +
	"\aentries\x18\x02 \x03(\v2\x0e.TimelineEntryR\aentries2\xcf\x04\n" +
	"\aMigawka\x12(\n" +
	"\bSayHello\x12\r.HelloRequest\x1a\v.HelloReply\"\x00\x122\n" +
	"\n" +
	"UploadFile\x12\x12.FileUploadRequest\x1a\x10.FileUploadReply\x128\n" +
	"\fDownloadFile\x12\x14.FileDownloadRequest\x1a\x12.FileDownloadReply\x12Y\n" +
	"\x1cGetThumbnailsBeforeTimestamp\x12\x1b.ThumbnailsTimestampRequest\x1a\x1c.ThumbnailsTimestampResponse\x12G\n" +
	"\x12GetTimelineEntries\x12\x17.TimelineEntriesRequest\x1a\x18.TimelineEntriesResponse\x12D\n" +
	"\x15GetOptimizedMediaItem\x12\x14.GetMediaItemRequest\x1a\x15.GetMediaItemResponse\x12;\n" +
	"\fGetThumbnail\x12\x14.GetMediaItemRequest\x1a\x15.GetMediaItemResponse\x12?\n" +
	"\x10GetFullMediaItem\x12\x14.GetMediaItemRequest\x1a\x15.GetMediaItemResponse\x12D\n" +
	"\x0fGetFileListPage\x12\x17.GetFileListPageRequest\x1a\x18.GetFileListPageResponseB,\n" +
	"\x13xyz.jdubiel.migawkaP\x01Z\x13migawka-server/grpcb\x06proto3"

var (
	file_grpc_grpc_proto_rawDescOnce sync.Once
	file_grpc_grpc_proto_rawDescData []byte
)

func file_grpc_grpc_proto_rawDescGZIP() []byte {
	file_grpc_grpc_proto_rawDescOnce.Do(func() {
		file_grpc_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_grpc_proto_rawDesc), len(file_grpc_grpc_proto_rawDesc)))
	})
	return file_grpc_grpc_proto_rawDescData
}

var file_grpc_grpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_grpc_grpc_proto_goTypes = []any{
	(DirectoryEntry_FileType)(0),        // 0: DirectoryEntry.FileType
	(*Status)(nil),                      // 1: Status
	(*HelloRequest)(nil),                // 2: HelloRequest
	(*HelloReply)(nil),                  // 3: HelloReply
	(*FileUploadRequest)(nil),           // 4: FileUploadRequest
	(*FileUploadReply)(nil),             // 5: FileUploadReply
	(*FileDownloadRequest)(nil),         // 6: FileDownloadRequest
	(*FileDownloadReply)(nil),           // 7: FileDownloadReply
	(*Thumbnail)(nil),                   // 8: Thumbnail
	(*ThumbnailsTimestampRequest)(nil),  // 9: ThumbnailsTimestampRequest
	(*ThumbnailsTimestampResponse)(nil), // 10: ThumbnailsTimestampResponse
	(*GetMediaItemRequest)(nil),         // 11: GetMediaItemRequest
	(*MediaItem)(nil),                   // 12: MediaItem
	(*GetMediaItemResponse)(nil),        // 13: GetMediaItemResponse
	(*GetFileListPageRequest)(nil),      // 14: GetFileListPageRequest
	(*GetFileListPageResponse)(nil),     // 15: GetFileListPageResponse
	(*DirectoryEntry)(nil),              // 16: DirectoryEntry
	(*TimelineEntry)(nil),               // 17: TimelineEntry
	(*TimelineEntriesRequest)(nil),      // 18: TimelineEntriesRequest
	(*TimelineEntriesResponse)(nil),     // 19: TimelineEntriesResponse
}
var file_grpc_grpc_proto_depIdxs = []int32{
	1,  // 0: ThumbnailsTimestampResponse.status:type_name -> Status
	8,  // 1: ThumbnailsTimestampResponse.thumbnails:type_name -> Thumbnail
	1,  // 2: GetMediaItemResponse.status:type_name -> Status
	12, // 3: GetMediaItemResponse.mediaItem:type_name -> MediaItem
	1,  // 4: GetFileListPageResponse.status:type_name -> Status
	16, // 5: GetFileListPageResponse.entries:type_name -> DirectoryEntry
	0,  // 6: DirectoryEntry.type:type_name -> DirectoryEntry.FileType
	8,  // 7: DirectoryEntry.thumbnail:type_name -> Thumbnail
	1,  // 8: TimelineEntriesResponse.status:type_name -> Status
	17, // 9: TimelineEntriesResponse.entries:type_name -> TimelineEntry
	2,  // 10: Migawka.SayHello:input_type -> HelloRequest
	4,  // 11: Migawka.UploadFile:input_type -> FileUploadRequest
	6,  // 12: Migawka.DownloadFile:input_type -> FileDownloadRequest
	9,  // 13: Migawka.GetThumbnailsBeforeTimestamp:input_type -> ThumbnailsTimestampRequest
	18, // 14: Migawka.GetTimelineEntries:input_type -> TimelineEntriesRequest
	11, // 15: Migawka.GetOptimizedMediaItem:input_type -> GetMediaItemRequest
	11, // 16: Migawka.GetThumbnail:input_type -> GetMediaItemRequest
	11, // 17: Migawka.GetFullMediaItem:input_type -> GetMediaItemRequest
	14, // 18: Migawka.GetFileListPage:input_type -> GetFileListPageRequest
	3,  // 19: Migawka.SayHello:output_type -> HelloReply
	5,  // 20: Migawka.UploadFile:output_type -> FileUploadReply
	7,  // 21: Migawka.DownloadFile:output_type -> FileDownloadReply
	10, // 22: Migawka.GetThumbnailsBeforeTimestamp:output_type -> ThumbnailsTimestampResponse
	19, // 23: Migawka.GetTimelineEntries:output_type -> TimelineEntriesResponse
	13, // 24: Migawka.GetOptimizedMediaItem:output_type -> GetMediaItemResponse
	13, // 25: Migawka.GetThumbnail:output_type -> GetMediaItemResponse
	13, // 26: Migawka.GetFullMediaItem:output_type -> GetMediaItemResponse
	15, // 27: Migawka.GetFileListPage:output_type -> GetFileListPageResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_grpc_grpc_proto_init() }
func file_grpc_grpc_proto_init() {
	if File_grpc_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_grpc_proto_rawDesc), len(file_grpc_grpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_grpc_proto_goTypes,
		DependencyIndexes: file_grpc_grpc_proto_depIdxs,
		EnumInfos:         file_grpc_grpc_proto_enumTypes,
		MessageInfos:      file_grpc_grpc_proto_msgTypes,
	}.Build()
	File_grpc_grpc_proto = out.File
	file_grpc_grpc_proto_goTypes = nil
	file_grpc_grpc_proto_depIdxs = nil
}
