syntax = "proto3";

option go_package = "migawka-server/grpc";

option java_package = "xyz.jdubiel.migawka";
option java_multiple_files = true;

// package helloworld;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
  rpc UploadFile(FileUploadRequest) returns (FileUploadReply);
  rpc DownloadFile(FileDownloadRequest) returns (FileDownloadReply);
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}

message FileUploadRequest {
  string filename = 1;
  bytes content = 2;
}

message FileUploadReply {
  string message = 1;
}

message FileDownloadRequest {
  string filename = 1;
}

message FileDownloadReply {
  string filename = 1;
  bytes content = 2;
  string message = 3;
}

