syntax = "proto3";

option go_package = "migawka-server/grpc";

option java_package = "xyz.jdubiel.migawka";
option java_multiple_files = true;

// package helloworld;

// The greeting service definition.
service Migawka {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
  rpc UploadFile(FileUploadRequest) returns (FileUploadReply);
  rpc DownloadFile(FileDownloadRequest) returns (FileDownloadReply);
  rpc GetThumbnailsBeforeTimestamp(ThumbnailsTimestampRequest) returns (ThumbnailsTimestampResponse);
  rpc GetTimelineEntries(TimelineEntriesRequest) returns (TimelineEntriesResponse);
  rpc GetOptimizedMediaItem(GetMediaItemRequest) returns (GetMediaItemResponse);
  rpc GetThumbnail(GetMediaItemRequest) returns (GetMediaItemResponse);
  rpc GetFullMediaItem(GetMediaItemRequest) returns (GetMediaItemResponse);
  rpc GetFileList(GetFileListRequest) returns (GetFileListResponse);
  rpc GetFullMetadata(FullMetadataRequest) returns (FullMetadataReply);

  // Client-side stream: Client sends many messages, Server returns one response
  rpc UploadPhotos(stream UploadRequest) returns (UploadResponse);
}

message UploadRequest {
  oneof request {
    UploadMetadata metadata = 1;
    bytes chunk = 2;
  }
}

message UploadMetadata {
  string id = 1;
  string creation_time = 2;
  bytes content = 3;
  string filename = 4;

  int32 total_photos = 5;
}

message UploadResponse {
  Status status = 1;
}

message Status {
  int32 code = 1;
  string message = 2;
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}

message FileUploadRequest {
  string filename = 1;
  bytes content = 2;
}

message FileUploadReply {
  string message = 1;
}

message FileDownloadRequest {
  string filename = 1;
}

message FileDownloadReply {
  string filename = 1;
  bytes content = 2;
  string message = 3;
}

message Thumbnail {
  // hash
  string id = 1;

  bytes content = 2;

  // ISO 8601
  string creationTime = 3;
}

message ThumbnailsTimestampRequest {
  // ISO 8601 (e.g., "2025-11-11T13:45:30Z")
  string timestamp = 1;

  // at most how many thumbnails should be returned
  uint32 count = 2;
}

message ThumbnailsTimestampResponse {
  Status status = 1;
  repeated Thumbnail thumbnails = 2;
}

message GetMediaItemRequest {
  string id = 1;
}

message MediaItem {
  string id = 1;
  string creationTime = 2;
  bytes content = 3;

  // Optional. Rooted at `mediadir` directory, without a leading `/`. 
  string path = 4; // optional
}

message GetMediaItemResponse {
  Status status = 1;

  MediaItem mediaItem = 2;
}

message GetFileListRequest {
  string path = 1;
}

message GetFileListResponse {
  Status status = 1;
  repeated DirectoryEntry entries = 2;
}

message DirectoryEntry {
  enum FileType {
    DIRECTORY = 0;
    MEDIA = 1;
    OTHER = 2; // symlinks are treated as files
  }

  FileType type = 1;
  string name = 2;

  // for media files, currently only images
  TimelineEntry media = 3;
}

message TimelineEntry {
  // hash
  string id = 1;

  // ISO 8601
  string creationTime = 2;
}

message TimelineEntriesRequest {
}

message TimelineEntriesResponse {
  Status status = 1;
  repeated TimelineEntry entries = 2;
}

message FullMetadataRequest {
  string id = 1;
}

enum MetadataKey {
  Exif_DateTime = 0;
  Exif_Make = 1;
  Exif_Model = 2;
  Exif_Orientation = 3;
  Exif_FocalLength = 4;
  Exif_ExposureTime = 5;
  Exif_FNumber = 6;
  Exif_ISO = 7;
  Exif_Flash = 8;
  Exif_WhiteBalance = 9;
  ID = 10;
  Path = 11;
  CreationDate = 12;
}


message FullMetadataReply {
  Status status = 1;

  // key(int32) is MetadataKey! 
  map<int32, string> values = 2;
}