syntax = "proto3";

option go_package = "migawka-server/grpc";

option java_package = "xyz.jdubiel.migawka";
option java_multiple_files = true;

// package helloworld;

// The greeting service definition.
service Migawka {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
  rpc UploadFile(FileUploadRequest) returns (FileUploadReply);
  rpc DownloadFile(FileDownloadRequest) returns (FileDownloadReply);
  rpc GetThumbnailsBeforeTimestamp(ThumbnailsTimestampRequest) returns (ThumbnailsTimestampResponse);
  rpc GetOptimizedMediaItem(GetMediaItemRequest) returns (GetMediaItemResponse);
  rpc GetFullMediaItem(GetMediaItemRequest) returns (GetMediaItemResponse);
  rpc GetFileListPage(GetFileListPageRequest) returns (GetFileListPageResponse);
}

message Status {
  int32 code = 1;
  string message = 2;
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}

message FileUploadRequest {
  string filename = 1;
  bytes content = 2;
}

message FileUploadReply {
  string message = 1;
}

message FileDownloadRequest {
  string filename = 1;
}

message FileDownloadReply {
  string filename = 1;
  bytes content = 2;
  string message = 3;
}

message Thumbnail {
  // hash
  string id = 1;

  bytes content = 2;

  // ISO 8601
  string creationTime = 3;
}

message ThumbnailsTimestampRequest {
  // ISO 8601 (e.g., "2025-11-11T13:45:30Z")
  string timestamp = 1;

  // at most how many thumbnails should be returned
  uint32 count = 2;
}

message ThumbnailsTimestampResponse {
  Status status = 1;
  repeated Thumbnail thumbnails = 2;
}

message GetMediaItemRequest {
  string id = 1;
}

message MediaItem {
  string id = 1;
  string creationTime = 2;
  bytes content = 3;

  // Optional. Rooted at `mediadir` directory, without a leading `/`. 
  string path = 4; // optional
}

message GetMediaItemResponse {
  Status status = 1;

  MediaItem mediaItem = 2;
}

message GetFileListPageRequest {
  string path = 1;
  uint32 pageNumber = 2;
  uint32 pageSize = 3;
}

message GetFileListPageResponse {
  Status status = 1;
  repeated DirectoryEntry entries = 2;
}

message DirectoryEntry {
  enum FileType {
    DIRECTORY = 0;
    REGULAR = 1; // symlinks are treated as files
  }

  FileType type = 1;
  string name = 2;

  // for image files
  MediaItem mediaItem = 3;
}



// message GetMediaItemByPathRequest {

// }
