services:
  golang-server:
    build: .
    ports:
      - "50051:50051"
      # It is important to use [ CMD ] form of `command` - it correctly sends
      # signals to the process when container is stopped. Running as `sh -c CMD`
      # will not allow for graceful shutdown!
    command: [ "./main", 
      "--mediadir", "/media",
      "--dbpath", "/db/migawka.sqlite",
      "--loglevel", "info",

      # Use plaintext (insecure!) or TLS
      # "--insecure-no-tls"
      "--tls-private-key", "/certs/migawka_server.key.pem",
      "--tls-cert", "/certs/migawka_server.crt"
    ]
    volumes:
      - /home/kuba/migawka_media3:/media
      - /home/kuba/migawka/certs:/certs
      - /home/kuba/migawka_server/db:/db
    environment:
      - CLIENT_TOKENS=first-secret-token,second-secret-token
